GET http://localhost:3000
###
GET http://localhost:3000/api/todos/2
###


POST http://localhost:3000 HTTP/1.1
message: "Hello"
id: 2
 
 ###

 POST url HTTP/1.1
 header name: header value
 
 content
 message: wow
 

